Prod-14 Footer component created
prodevshub/community-blog pull request #12
Opened 2022-05-31 17:33 UTC by suiraDN

2022-05-31 18:08 UTC, MarcinkEve approved these changes

2022-05-31 20:11 UTC, prodevshub requested changes

2022-05-31 20:11 UTC, prodevshub commented on src/Components/Footer/Footer.jsx
> +            <span>Copyright © 2022 community blog. All Rights Reserved</span>
Please use new Date().getFullYear() to get years, otherwise we will have to edit this code each January 1st :)

2022-05-31 20:11 UTC, prodevshub commented on src/Components/Footer/Footer.jsx
> +        <div className="footer_main_box">
Please use BEM css methodology: https://en.bem.info/methodology/
this class you can change to footer__main-box

2022-05-31 20:11 UTC, prodevshub commented on src/Components/Footer/Footer.jsx
> +            <div className="footer_first_block">
footer__first-block

2022-05-31 20:11 UTC, prodevshub commented on src/Components/Footer/Footer.jsx
> +            <div className="footer_second_block">
footer__second-block

2022-05-31 20:11 UTC, prodevshub commented on src/Components/Footer/Footer.jsx
> +        <div className="footer_copyright">
footer__copyright-block

2022-05-31 20:11 UTC, prodevshub commented on src/Components/Footer/Footer.scss
> +.footer {
We should use SASS syntax:
```
.footer {
  width: 100%;
  min-height: auto;
  background-color: #0d3700d8;
  font-family: $fontBitter;
     &__main-box {
       	width: auto;
	color: #fff;
	text-align: center;
	display: flex;
	flex-direction: row;
	align-items: center;
	justify-content: space-around;
	padding: 15px;
     }
       ... etc
}
```

2022-05-31 20:11 UTC, prodevshub commented on src/Components/Footer/index.js
> +export { default } from "./Footer";
If readme.md is empty file, it should be deleted.

2022-06-02 07:34 UTC, prodevshub approved these changes

2022-06-02 07:34 UTC, merged