PROD-5
prodevshub/community-blog pull request #4
Opened 2022-05-25 17:26 UTC by MarcinkEve

[PROD-2](https://prodevshub.atlassian.net/browse/PROD-2)

[PROD-5](https://prodevshub.atlassian.net/browse/PROD-5)

2022-05-25 18:47 UTC, prodevshub commented on src/App.css
>  }
This file shouldn't be changed.  They should be exact as it is in main branch. Please reverse them to original.

2022-05-25 18:47 UTC, prodevshub commented on src/App.jsx
> +import "./App.css";
This file shouldn't be changed.  They should be exact as it is in main branch. Please reverse them to original.

2022-05-25 18:53 UTC, prodevshub commented
You need to resolve conflicts in order to merge this PR.

2022-05-25 18:53 UTC, prodevshub requested changes
Please resolve issues regarding this PR by resolving conflicts with main branch

2022-05-26 18:21 UTC, prodevshub approved these changes

2022-05-26 18:33 UTC, SwallowEve approved these changes
Nice done, Evelina!

2022-05-26 18:37 UTC, INKR1 approved these changes
Good job :)

2022-05-27 11:28 UTC, merged